run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - nlreturn
    - nonamedreturns
    - mnd
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - 'package-comments: should have a package comment'
