version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - mnd
    - nlreturn
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 15
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
                skip-package-name-collision-with-go-std: true
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
