version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
