version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.24
    environment:
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
    ports:
      - "6831:6831/udp"
      - "9411:9411"
      - "16686:16686"