[[constraint]]
  name = "github.com/msales/pkg"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.*"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.*"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.*"
