---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ren
  labels:
    app: ren
spec:
  selector:
    matchLabels:
      app: ren
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ren
    spec:
      containers:
        - name: ren
          image: ren:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
