on:
  push:
    branches:
      - main
  pull_request:

name: run tests
jobs:
  test:

    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v1.64.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Run tests
        run: go test -covermode=count -coverprofile=coverage.out ./...

      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1

      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --snapshot
